@startuml
skinparam linetype ortho

class Cliente {
  - nome: String
  - nomedeUsuario: String
  - senha: String
  - listaParaVer: Lista<Midia>
  - listaJaVistas: Lista<Midia>
  ..
  + adicionarNaLista(Midia): void
  + retirarDaLista(String): void
  + registraAudiencia(Midia): void
  + imprimeListParaVer(): void
}

abstract class Midia {
  + {static} GENEROS: String[]
  # id: int
  # nome: String
  # genero: String
  # idioma: String
  # audiencia: int
  # dataLancamento: String
  # nota: int
  ..
  + {static} gerarGeneroAleatorio(): String
  + registraAudiencia(): int
  + avaliarMidia(int): void
}

class Filme{
  - idFilme: int
  - duracao: int
  ..
  +Filme(int, int): void
}

class Serie {
  - idSerie: int
  - quantidadeDeEpsodios: int
  ..
}

class PlataformaStreaming {
  - nome: String
  - midias: List<Midia>
  - clienteAtual: Cliente
  - clientes: List<Cliente>
  ..
  + adicionarCliente(Cliente): void
  + buscarSerie(String): Midia
  + carregarEspectador(String): void
  + carregarSeries(String): void
  + carregarFilmes(String): void
  + carregarAudiencia(String): void
  + login(String, String): Cliente
  + adicionarmidia(Midia): void
  + adicionarCliente((Cliente): void
  + filtrarPorGenero(String): List<Midia>
  + filtrarPorIdioma(String): List<Midia>
  + registraAudiencia(Midia): void
  + logoff(): void
  + buscarMidia(String): Midia
  + filtrarPorQntEps(int): List<Serie>
}

Filme --|> Midia
Serie --|> Midia
Midia <-- PlataformaStreaming
Cliente <-- PlataformaStreaming
@enduml