@startuml
skinparam linetype ortho
skinparam classAttributeIconSize 0

class Avaliacao {
  - nota: int
  - comentario: String
  ..
  + Avaliacao(int, String)
  + Avaliacao(int)
}

class Cliente {
  + Cliente():
  + Cliente(String, String, String):
  ~ nomedeUsuario: String
  ~ senha: String
  - nome: String
  - listaJaVistas: List<Midia>
  - listaParaVer: List<Midia>
  ..
  + filtrarJaVistasPorIdioma(String): ArrayList<Midia>
  + ehAdmin(): boolean
  + filtrarListaParaVer(String): ArrayList<Midia>
  + filtrarJaVistasPorGenero(String): ArrayList<Midia>
  + imprimeListaJaVistas(): void
  + imprimeListaParaVer(): void
  + registrarAudiencia(Midia, String): void
  + filtrarParaVerPorGenero(String): ArrayList<Midia>
  + ehClienteEspecialista(): boolean
  + filtrarListaJaVistas(String): ArrayList<Midia>
  + retirarDaLista(String): void
  + filtrarParaVerPorIdioma(String): ArrayList<Midia>
  + toString(): String
  + adicionarNaLista(Midia): void
}

class Filme {
  - idFilme: int
  + toString(): String
  ..
  + Filme(String, String, String, int, String):
}

class Midia {
  + Midia():
  # dataLancamento: String
  # genero: String
  # ultimoId: int
  # nome: String
  # idioma: String
  # audiencia: int
  ..
  + registrarAvaliacaoComentario(String, int, String): void
  + gerarGeneroAleatorio(): String
  + registraAudiencia(): int
  + verificaAvaliacaoRegistrada(String): boolean
  + registrarAvaliacao(String, int): void
  + gerarIdiomaAleatorio(): String
}

class PlataformaStreaming {
  + PlataformaStreaming():
  + PlataformaStreaming(String):
  - clientes: List<Cliente>
  - midias: List<Midia>
  - nome: String
  - clienteAtual: Cliente
  ..
  + carregarSeries(String): void
  + buscarMidia(int): Midia
  + filtrarPorGenero(String): ArrayList<Midia>
  + filtrarPorIdioma(String): ArrayList<Midia>
  + adicionarCliente(Cliente): void
  + filtrarPorQntEps(int): List<Serie>
  + carregarAudiencia(String): void
  + registrarAudiencia(Midia): int
  + atualizarArquivo(String, String): void
  + logoff(): void
  + adicionarMidia(Midia): void
  + avaliar(Midia, int): void
  + carregarEspectador(String): void
  + filtrarPorNome(String): ArrayList<Midia>
  + login(String, String): Cliente
  + buscarMidia(String): Midia
  + carregarFilmes(String): void
}

class Serie {
  - quantidadeDeEpsodios: int
  - idSerie: int
  ..
  + Serie(String, String, String, int, String):
  + toString(): String
}

Midia  <--  PlataformaStreaming
Midia  <|--  Filme
Serie  --|>  Midia
Avaliacao  <--*  Midia
Filme  <--  PlataformaStreaming
Serie  <--  PlataformaStreaming
Cliente  *-->  Midia
PlataformaStreaming  *--> Cliente
@enduml